name: Write Terraform Plan to Pull Request

on:
  pull_request:
    branches:
      - main  # or any other branch you want to trigger the deployment
    paths: 
      - '**/*.tf'

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    permissions:
      id-token: write
      contents: read
      pull-requests: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::035866691871:role/devops-security-tf-plan
        role-session-name: devopssecuritytfplan
        aws-region: us-west-2

    - name: Terraform Plan
      uses: dflook/terraform-plan@v1
      with:
        path: terraform
        backend_config_file: terraform/prod.backend.tfvars
